"""
PDF contract generator using WeasyPrint.
WeasyPrint is lazy-loaded to prevent import failures when system dependencies are missing.
"""
import hashlib
import os
from datetime import datetime
from typing import Dict, Any, Optional, Tuple
from jinja2 import Template
from app.core.config import settings


class PDFContractGenerator:
    """Generate PDF contracts from templates"""
    
    CONTRACT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Escrow Contract</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .section {
            margin-bottom: 25px;
        }
        .section-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #333;
        }
        .party-info {
            background-color: #f5f5f5;
            padding: 15px;
            margin: 10px 0;
            border-left: 4px solid #333;
        }
        .terms {
            margin: 15px 0;
            padding: 15px;
            background-color: #fafafa;
        }
        .signature-section {
            margin-top: 40px;
            border-top: 1px solid #ccc;
            padding-top: 20px;
        }
        .signature-line {
            margin-top: 60px;
            border-top: 1px solid #333;
            width: 300px;
        }
        .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #666;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ESCROW ACCOUNT TRANSFER AGREEMENT</h1>
        <p>Contract Date: {{ contract_date }}</p>
    </div>
    
    <div class="section">
        <div class="section-title">PARTIES</div>
        <div class="party-info">
            <strong>Seller:</strong> {{ seller_name }}<br>
            <strong>Email:</strong> {{ seller_email }}
        </div>
        <div class="party-info">
            <strong>Buyer:</strong> {{ buyer_name }}<br>
            <strong>Email:</strong> {{ buyer_email }}
        </div>
    </div>
    
    <div class="section">
        <div class="section-title">LISTING DETAILS</div>
        <p><strong>Platform:</strong> {{ platform }}</p>
        <p><strong>Category:</strong> {{ category }}</p>
        <p><strong>Title:</strong> {{ listing_title }}</p>
        <p><strong>Purchase Price:</strong> ${{ purchase_price }}</p>
    </div>
    
    <div class="section">
        <div class="section-title">TERMS AND CONDITIONS</div>
        <div class="terms">
            <p><strong>1. ESCROW PROTECTION</strong></p>
            <p>Funds are held in escrow until buyer confirms successful access to the account. 
            Funds will be released to seller only after buyer confirms access.</p>
            
            <p><strong>2. NO REFUND POLICY</strong></p>
            <p>Once buyer confirms access and funds are released, no refunds will be issued. 
            Buyer assumes all responsibility for account usage and compliance with platform Terms of Service.</p>
            
            <p><strong>3. ASSUMPTION OF RISK</strong></p>
            <p>Buyer acknowledges that account transfers may violate platform Terms of Service. 
            Buyer assumes all risk and liability for any consequences arising from this transaction.</p>
            
            <p><strong>4. CREDENTIAL RELEASE</strong></p>
            <p>Credentials will be released to buyer only after contract is signed and payment is confirmed. 
            Credentials are shown once and must be saved securely by buyer.</p>
            
            <p><strong>5. DISPUTE RESOLUTION</strong></p>
            <p>Any disputes must be raised within 48 hours of credential release. 
            Escrow platform will mediate disputes in good faith.</p>
        </div>
    </div>
    
    <div class="section signature-section">
        <div class="section-title">ELECTRONIC SIGNATURE</div>
        <p>By typing your full legal name below, you agree to be bound by the terms of this contract.</p>
        {% if signed_by_name %}
        <p><strong>Signed by:</strong> {{ signed_by_name }}</p>
        <p><strong>Signed at:</strong> {{ signed_at }}</p>
        {% else %}
        <p><em>Contract pending signature</em></p>
        {% endif %}
    </div>
    
    <div class="footer">
        <p>This contract is generated by ESCROW platform and is legally binding.</p>
        <p>Contract Hash: {{ contract_hash }}</p>
        <p>Generated: {{ generated_at }}</p>
    </div>
</body>
</html>
"""
    
    @staticmethod
    def generate_contract(
        seller_name: str,
        seller_email: str,
        buyer_name: str,
        buyer_email: str,
        listing_title: str,
        platform: str,
        category: str,
        purchase_price: float,
        signed_by_name: Optional[str] = None,
        signed_at: Optional[str] = None
    ) -> tuple[bytes, str]:
        """
        Generate PDF contract.
        
        Args:
            seller_name: Seller's full name
            seller_email: Seller's email
            buyer_name: Buyer's full name
            buyer_email: Buyer's email
            listing_title: Listing title
            platform: Platform name (Upwork, Fiverr, etc.)
            category: Category name
            purchase_price: Price in USD
            signed_by_name: Buyer's signature name (if signed)
            signed_at: Signature timestamp (if signed)
            
        Returns:
            Tuple of (pdf_bytes, contract_hash)
        """
        # Prepare template data
        contract_date = datetime.utcnow().strftime("%B %d, %Y")
        generated_at = datetime.utcnow().isoformat()
        
        template_data = {
            "contract_date": contract_date,
            "seller_name": seller_name,
            "seller_email": seller_email,
            "buyer_name": buyer_name,
            "buyer_email": buyer_email,
            "listing_title": listing_title,
            "platform": platform,
            "category": category,
            "purchase_price": f"{purchase_price:.2f}",
            "signed_by_name": signed_by_name,
            "signed_at": signed_at,
            "generated_at": generated_at,
            "contract_hash": ""  # Will be set after generation
        }
        
        # Render HTML template
        template = Template(PDFContractGenerator.CONTRACT_TEMPLATE)
        html_content = template.render(**template_data)
        
        # Lazy-load WeasyPrint to prevent import failures when system deps are missing
        try:
            from weasyprint import HTML
        except ImportError as e:
            raise ImportError(
                "WeasyPrint is not available. Install system dependencies:\n"
                "  macOS: brew install cairo pango gdk-pixbuf libffi glib\n"
                "  Ubuntu: sudo apt-get install python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0\n"
                f"Original error: {str(e)}"
            )
        
        # Generate PDF
        html = HTML(string=html_content)
        pdf_bytes = html.write_pdf()
        
        # Calculate SHA-256 hash
        contract_hash = hashlib.sha256(pdf_bytes).hexdigest()
        
        # Update template with hash (for display in PDF)
        template_data["contract_hash"] = contract_hash
        html_content = template.render(**template_data)
        html = HTML(string=html_content)
        pdf_bytes = html.write_pdf()
        
        return pdf_bytes, contract_hash
    
    @staticmethod
    def save_pdf_to_storage(pdf_bytes: bytes, transaction_id: int) -> str:
        """
        Save PDF to storage (Cloudinary or S3).
        For now, returns a placeholder URL.
        In production, upload to Cloudinary/S3.
        
        Args:
            pdf_bytes: PDF file bytes
            transaction_id: Transaction ID
            
        Returns:
            PDF URL
        """
        # TODO: Implement Cloudinary/S3 upload
        # For now, return placeholder
        return f"https://storage.escrow.com/contracts/{transaction_id}.pdf"

